baseurl = "/"
languageCode = "nl-nl"
languageLang = "nl"
title = "Afdeling Publieksfrustratie"
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

[params]
images = ["https://images.pexels.com/photos/8297217/pexels-photo-8297217.jpeg"]
